### ISSUE TITLE
[bug] Standalone subtitle extraction fails but works as part of library scan

### ISSUE THREAD

**Issue by secondary02** [jellyfin/jellyfin-plugin-subtitleextract#36]
Server version: 10.9.9
OS: Windows 10

I installed the Subtitle Extract plugin. Subtitle extraction fails when triggered from Scheduled Tasks tab but works fine when running as part of the Library Scan when the option is enabled in plugin settings.

Sample failure logs:

```
[2024-08-21 00:06:17.570 +05:30] [INF] [25] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: "ffmpeg" "-i \"Z:\movies4k\Dune.Part.Two.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR\Dune.Part.Two.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR.mkv\" -copyts -map 0:3 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\5\5ed9dc4e-0ae0-92ff-081f-7d55aabd0445.srt\" -map 0:5 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\d\df9e08b9-dc74-0bd5-73d3-5ee4622dcdf5.srt\" -map 0:6 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\5\59ad285b-6c7f-3697-075e-0d2f75cd0dd5.srt\" -map 0:7 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\c\cd728bec-86c6-1f5b-c65a-463bb3f642e2.srt\" -map 0:8 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\3\36e9d8ce-d512-0d8f-d07c-b36cf1a5bced.srt\" -map 0:10 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\8\8e7cf824-f463-7db4-916b-efe55c249029.srt\" -map 0:13 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\2\20302b35-dc4d-2223-78e0-d1e3b8a911eb.srt\" -map 0:14 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\0\0ff674ff-8611-7c85-9d94-665dcd341321.srt\" -map 0:15 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\5\5c530b3d-1e89-c8f2-269e-62a089156e4c.srt\" -map 0:16 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\0\0ebe9f1a-8947-f41d-a8ba-074607c50cac.srt\" -map 0:17 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\a\aaecde58-d38a-a31b-2974-61c185fb7f8b.srt\" -map 0:18 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\0\0ca9b679-4fa3-4cbb-d184-ab81975b5a0e.srt\" -map 0:19 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\6\66058c34-5f85-ee7f-5008-f153b250f93e.srt\" -map 0:20 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\3\3bac2a89-951f-73cf-97e6-fd9e73f0a467.srt\" -map 0:21 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\1\1c26cd92-cb6b-f35c-1391-e6a46d40a0d8.srt\" -map 0:22 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\7\70404f6f-dba8-59d8-1c46-4dda785d8e6c.srt\" -map 0:24 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\e\ea8ab1e8-6cad-4c74-184a-8616e2e738c8.srt\" -map 0:25 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\0\0b9d6fbc-7c22-c45c-0861-2d476600c49f.srt\" -map 0:26 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\8\8bdcc65d-7f38-4d12-4b31-af5738ae93ea.srt\" -map 0:27 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\c\cf55db3c-3a18-4188-ca75-c4a868f6d909.srt\" -map 0:28 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\9\913789d1-a26c-53eb-7721-1d1386b6ee62.srt\" -map 0:29 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\7\7a1b492e-2296-411b-689c-8e76f8c3c4c8.srt\" -map 0:30 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\0\020e2a42-29d5-7f42-ac6e-ba888122f9e8.srt\" -map 0:33 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\f\f8365e01-b0e4-66e6-b2b9-e877053eaac1.srt\" -map 0:34 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\0\058a70a9-f73f-1be2-a40d-bef0e97da94e.srt\""
[2024-08-21 00:36:17.706 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\5\5ed9dc4e-0ae0-92ff-081f-7d55aabd0445.srt"
[2024-08-21 00:36:17.710 +05:30] [ERR] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Error deleting extracted subtitle "C:\ProgramData\Jellyfin\Server\data\subtitles\5\5ed9dc4e-0ae0-92ff-081f-7d55aabd0445.srt"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\data\subtitles\5\5ed9dc4e-0ae0-92ff-081f-7d55aabd0445.srt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
[2024-08-21 00:36:17.716 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\d\df9e08b9-dc74-0bd5-73d3-5ee4622dcdf5.srt"
[2024-08-21 00:36:17.720 +05:30] [ERR] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Error deleting extracted subtitle "C:\ProgramData\Jellyfin\Server\data\subtitles\d\df9e08b9-dc74-0bd5-73d3-5ee4622dcdf5.srt"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\data\subtitles\d\df9e08b9-dc74-0bd5-73d3-5ee4622dcdf5.srt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
[2024-08-21 00:36:17.726 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\5\59ad285b-6c7f-3697-075e-0d2f75cd0dd5.srt"
[2024-08-21 00:36:17.729 +05:30] [ERR] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Error deleting extracted subtitle "C:\ProgramData\Jellyfin\Server\data\subtitles\5\59ad285b-6c7f-3697-075e-0d2f75cd0dd5.srt"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\data\subtitles\5\59ad285b-6c7f-3697-075e-0d2f75cd0dd5.srt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
[2024-08-21 00:36:17.735 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\c\cd728bec-86c6-1f5b-c65a-463bb3f642e2.srt"
[2024-08-21 00:36:17.738 +05:30] [ERR] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Error deleting extracted subtitle "C:\ProgramData\Jellyfin\Server\data\subtitles\c\cd728bec-86c6-1f5b-c65a-463bb3f642e2.srt"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\data\subtitles\c\cd728bec-86c6-1f5b-c65a-463bb3f642e2.srt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
[2024-08-21 00:36:17.743 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\3\36e9d8ce-d512-0d8f-d07c-b36cf1a5bced.srt"
[2024-08-21 00:36:17.747 +05:30] [ERR] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Error deleting extracted subtitle "C:\ProgramData\Jellyfin\Server\data\subtitles\3\36e9d8ce-d512-0d8f-d07c-b36cf1a5bced.srt"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\data\subtitles\3\36e9d8ce-d512-0d8f-d07c-b36cf1a5bced.srt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
[2024-08-21 00:36:17.752 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\8\8e7cf824-f463-7db4-916b-efe55c249029.srt"
[2024-08-21 00:36:17.756 +05:30] [ERR] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Error deleting extracted subtitle "C:\ProgramData\Jellyfin\Server\data\subtitles\8\8e7cf824-f463-7db4-916b-efe55c249029.srt"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\data\subtitles\8\8e7cf824-f463-7db4-916b-efe55c249029.srt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
[2024-08-21 00:36:17.761 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\2\20302b35-dc4d-2223-78e0-d1e3b8a911eb.srt"
[2024-08-21 00:36:17.764 +05:30] [ERR] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Error deleting extracted subtitle "C:\ProgramData\Jellyfin\Server\data\subtitles\2\20302b35-dc4d-2223-78e0-d1e3b8a911eb.srt"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\data\subtitles\2\20302b35-dc4d-2223-78e0-d1e3b8a911eb.srt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
[2024-08-21 00:36:17.770 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\0\0ff674ff-8611-7c85-9d94-665dcd341321.srt"
[2024-08-21 00:36:17.775 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\5\5c530b3d-1e89-c8f2-269e-62a089156e4c.srt"
[2024-08-21 00:36:17.778 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\0\0ebe9f1a-8947-f41d-a8ba-074607c50cac.srt"
[2024-08-21 00:36:17.783 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\a\aaecde58-d38a-a31b-2974-61c185fb7f8b.srt"
[2024-08-21 00:36:17.786 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\0\0ca9b679-4fa3-4cbb-d184-ab81975b5a0e.srt"
[2024-08-21 00:36:17.790 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\6\66058c34-5f85-ee7f-5008-f153b250f93e.srt"
[2024-08-21 00:36:17.794 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\3\3bac2a89-951f-73cf-97e6-fd9e73f0a467.srt"
[2024-08-21 00:36:17.797 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\1\1c26cd92-cb6b-f35c-1391-e6a46d40a0d8.srt"
[2024-08-21 00:36:17.801 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\7\70404f6f-dba8-59d8-1c46-4dda785d8e6c.srt"
[2024-08-21 00:36:17.804 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\e\ea8ab1e8-6cad-4c74-184a-8616e2e738c8.srt"
[2024-08-21 00:36:17.808 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\0\0b9d6fbc-7c22-c45c-0861-2d476600c49f.srt"
[2024-08-21 00:36:17.811 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\8\8bdcc65d-7f38-4d12-4b31-af5738ae93ea.srt"
[2024-08-21 00:36:17.815 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\c\cf55db3c-3a18-4188-ca75-c4a868f6d909.srt"
[2024-08-21 00:36:17.818 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\9\913789d1-a26c-53eb-7721-1d1386b6ee62.srt"
[2024-08-21 00:36:17.822 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\7\7a1b492e-2296-411b-689c-8e76f8c3c4c8.srt"
[2024-08-21 00:36:17.825 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\0\020e2a42-29d5-7f42-ac6e-ba888122f9e8.srt"
[2024-08-21 00:36:17.829 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\f\f8365e01-b0e4-66e6-b2b9-e877053eaac1.srt"
[2024-08-21 00:36:17.832 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: "C:\ProgramData\Jellyfin\Server\data\subtitles\0\058a70a9-f73f-1be2-a40d-bef0e97da94e.srt"
[2024-08-21 00:36:17.836 +05:30] [WRN] [35] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Unable to get streams for File:"Z:\movies4k\Dune.Part.Two.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR\Dune.Part.Two.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR.mkv"
MediaBrowser.Common.FfmpegException: ffmpeg subtitle extraction failed for Z:\movies4k\Dune.Part.Two.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR\Dune.Part.Two.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR.mkv
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitles(MediaSourceInfo mediaSource, CancellationToken cancellationToken)

```

Successful extraction when triggered by library scan:

```
[2024-08-22 06:23:00.322 +05:30] [INF] [20] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Season Unknown" entry for "Brooklyn Nine-Nine"
[2024-08-22 06:23:00.591 +05:30] [INF] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E01.Honeymoon.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-08-22 06:23:10.314 +05:30] [INF] [64] Trakt.Helpers.LibraryManagerEventsHelper: Timer elapsed - processing queued items
[2024-08-22 06:23:10.321 +05:30] [INF] [64] Trakt.Helpers.LibraryManagerEventsHelper: No events... stopping queue timer
[2024-08-22 06:23:11.489 +05:30] [INF] [20] Jellyfin.Plugin.SubtitleExtract.Providers.SubsMetadataProvider: Extracting subtitles for: "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E01.Honeymoon.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv"
[2024-08-22 06:23:11.495 +05:30] [INF] [20] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: "ffmpeg" "-i \"Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E01.Honeymoon.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv\" -copyts -map 0:2 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\f\ff5f46dd-5325-0025-37fd-5bb0c1fb7e6c.srt\" -map 0:3 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\1\1174d8e8-4b70-6b3d-0d04-aa30c40f2093.srt\""
[2024-08-22 06:25:14.004 +05:30] [INF] [22] Emby.Server.Implementations.Updates.InstallationManager: Plugin "installed": "Webhook" "15.0.0.0"
[2024-08-22 06:25:14.018 +05:30] [INF] [22] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
[2024-08-22 06:25:42.159 +05:30] [INF] [19] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.6" closed
[2024-08-22 06:25:42.543 +05:30] [INF] [32] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.6" request
[2024-08-22 06:25:52.547 +05:30] [INF] [19] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.6" closed
[2024-08-22 06:25:52.764 +05:30] [INF] [20] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.6" request
[2024-08-22 06:26:26.960 +05:30] [INF] [20] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.6" closed
[2024-08-22 06:26:27.204 +05:30] [INF] [67] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.6" request
[2024-08-22 06:28:25.678 +05:30] [INF] [17] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-08-22 06:29:17.115 +05:30] [INF] [65] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction completed for "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E01.Honeymoon.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv" to "C:\ProgramData\Jellyfin\Server\data\subtitles\f\ff5f46dd-5325-0025-37fd-5bb0c1fb7e6c.srt"
[2024-08-22 06:29:17.123 +05:30] [INF] [65] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction completed for "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E01.Honeymoon.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv" to "C:\ProgramData\Jellyfin\Server\data\subtitles\1\1174d8e8-4b70-6b3d-0d04-aa30c40f2093.srt"
[2024-08-22 06:29:17.164 +05:30] [INF] [65] Jellyfin.Plugin.SubtitleExtract.Providers.SubsMetadataProvider: Finished subtitle extraction for: "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E01.Honeymoon.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv"
[2024-08-22 06:29:18.538 +05:30] [INF] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-08-22 06:29:28.530 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: Timer elapsed - processing queued items
[2024-08-22 06:29:28.550 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Remove to process
[2024-08-22 06:29:28.558 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Add to process
[2024-08-22 06:29:28.565 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Update to process
[2024-08-22 06:29:28.579 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Remove to process
[2024-08-22 06:29:28.583 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Add to process
[2024-08-22 06:29:28.587 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: Processing 1 episodes with event type Update
[2024-08-22 06:29:29.169 +05:30] [INF] [63] Jellyfin.Plugin.SubtitleExtract.Providers.SubsMetadataProvider: Extracting subtitles for: "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv"
[2024-08-22 06:29:29.183 +05:30] [INF] [63] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: "ffmpeg" "-i \"Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv\" -copyts -map 0:2 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\5\52d09d5e-dc5d-4bb9-8c32-ccb4e13c55b4.srt\" -map 0:3 -an -vn -c:s copy \"C:\ProgramData\Jellyfin\Server\data\subtitles\4\4290c7da-c740-b6a5-ec6e-ee01c4fa6f94.srt\""
[2024-08-22 06:29:30.090 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Remove to process
[2024-08-22 06:29:30.097 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Add to process
[2024-08-22 06:29:30.102 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Update to process
[2024-08-22 06:29:30.105 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Remove to process
[2024-08-22 06:29:30.108 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Add to process
[2024-08-22 06:29:30.111 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Update to process
[2024-08-22 06:29:30.113 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Remove to process
[2024-08-22 06:29:30.116 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Add to process
[2024-08-22 06:29:30.119 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: Processing 1 episodes with event type Update
[2024-08-22 06:29:30.438 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Remove to process
[2024-08-22 06:29:30.442 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Add to process
[2024-08-22 06:29:30.445 +05:30] [INF] [63] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Update to process
[2024-08-22 06:30:13.670 +05:30] [INF] [66] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-08-22 06:33:37.673 +05:30] [INF] [26] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-08-22 06:34:25.676 +05:30] [INF] [26] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-08-22 06:35:52.060 +05:30] [INF] [26] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction completed for "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv" to "C:\ProgramData\Jellyfin\Server\data\subtitles\5\52d09d5e-dc5d-4bb9-8c32-ccb4e13c55b4.srt"
[2024-08-22 06:35:52.070 +05:30] [INF] [26] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction completed for "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv" to "C:\ProgramData\Jellyfin\Server\data\subtitles\4\4290c7da-c740-b6a5-ec6e-ee01c4fa6f94.srt"
[2024-08-22 06:35:52.087 +05:30] [INF] [26] Jellyfin.Plugin.SubtitleExtract.Providers.SubsMetadataProvider: Finished subtitle extraction for: "Z:\shows\Brooklyn.Nine-Nine.S06.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP[rartv]\Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv"
```

Related forum post for additional information: https://forum.jellyfin.org/t-subtitle-extract-plugin-not-working

**Comment by crobibero** [comment]
This isn't an issue with the plugin since it just tells the server to extract "now" instead of waiting for playback to be attempted.

I would move this issue but the server issue template is more thorough

**Comment by secondary02** [comment]
I don't understand what you mean. Other people seem to be able to get the plugin to work without running as part of the library scan. Is there I can do on my end to get it working? Is this a genuine bug or an issue on my end?
